characters:
  characters:
    maurice:
      $ref: /characters/maurice
    taida:
      $ref: /characters/taida
    arran:
      $ref: /characters/arran
    roowk:
      $ref: /characters/roowk
    tariko:
      $ref: /characters/tariko
    khij:
      $ref: /characters/khij
    argek:
      $ref: /characters/argek
    khij20:
      $ref: /characters/khij20
    argek20:
      $ref: /characters/argek20
