repo:
  teams:
    read: []
    write: []
    admin: []
  external_collaborators: []
  inherit_external_collaborators: true
  access_keys: []
  default_branch: master
  branch_permissions:
    wildcards:  # TODO: Re-activate
      #- master
      #- release*
      #- next*
      []
    settings:
      enforce_admins: true,
      required_approving_review_count: 1,
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false
